### PR TITLE
Bump Optim.jl version

### PR DESCRIPTION
**Pull request by raphaelsaavedra**

### CODE REVIEW

**Comment by raphaelsaavedra** [comment]
Failing due to https://github.com/JuliaNLSolvers/Optim.jl/issues/863, we might need to update the julia `compat` to `1.2`

**Comment by guilhermebodin** [comment]
Lets merge this after 0.4 is released, a 0.4.1 version for example

**Comment by pkofod** [comment]
I think you should just depend on v1.2 here. v1.1 was unfortunately a bit buggy as the issue linked here shows. So you don't have to touch the other bounds, just the Optim one, and go for v1.2

**Comment by raphaelsaavedra** [comment]
Closing in favor of #227

**Pull request closed without merging**
